apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: x-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  ingressClassName: nginx
  rules:
    - host: $(host)
      http:
        paths:
          - path: $(url_path_folder)(/authentication/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: x-auth-api
                port:
                  number: 8080
          - path: $(url_path_folder)(/.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: x-addressbook-api
                port:
                  number: 8080

