apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: x-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
  - host: $(host)
    http:
      paths:

      # 1) Auth: strip folder, route /authentication/* → auth API
      - path: ^(/[^/]+)(/authentication/.*)$
        pathType: ImplementationSpecific
        backend:
          service:
            name: x-auth-api
            port:
              number: 8080

      # 2) All others: strip folder, route /* → addressbook API
      - path: ^(/[^/]+)(/.*)$
        pathType: ImplementationSpecific
        backend:
          service:
            name: x-addressbook-api
            port:
              number: 8080

